name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: install packages
      run: |
        pip install -r requirements.txt
    - run: pyinstaller --noconfirm --onefile --noconsole "./turtleHelper.py"
    - uses: actions/upload-artifact@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        path: |
          ./dist/*