name: Package Application with Pyinstaller

on:
  push:
    branches:
      test-virus-fp
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    # Build python script into a stand-alone exe
    - uses: Nuitka/Nuitka-Action@v0.4
      with:
        script-name: turtleHelper.py

    # Uploads artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe
        path: build/turtleHelper.exe