name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: install packages
      run: |
        pip install -r requirements.txt
    - run: pyinstaller --noconfirm --onefile --noconsole "./turtleHelper.py"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/*