name: Package Application with Pyinstaller

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest, 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    - name: install packages
      run: |
        pip install -r requirements.txt
    - run: pyinstaller --noconfirm --onefile --noconsole "./turtleHelper.py"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./dist/*